### ISSUE TITLE
Image resolver

### ISSUE THREAD

**Issue by matap** [Kentico/kentico-cloud-js#109]
### Motivation

I need to transform images, which are in rich text editor. Eg to set max width and type of image by adding query string "w=1200&auto=format"

### Proposed solution

Mayme the best solution is to add resolver for images

### Additional context

All of supported transformations: https://developer.kenticocloud.com/v1/reference#image-transformation

**Comment by Enngage** [comment]
Implemented in `1.4.0`. See https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/DOCS.md#image-processing-inside-rich-text-fields

**Comment by matap** [comment]
Thank you
