### ISSUE TITLE
HTML & UMD code example results in console error

### ISSUE THREAD

**Issue by kentico-michaelb** [Kentico/kentico-cloud-js#113]
Following the HTML & UMD example here: [ https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/DOCS.md#quick-start-html--umd]( https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/DOCS.md#quick-start-html--umd) I receive the console error: `Uncaught TypeError: Cannot read property 'DeliveryClient' of undefined` when opening the .html file in a browser.

Using the attached markup (as a .html file) works correctly.
[kc_JS.txt](https://github.com/Kentico/kentico-cloud-js/files/2876405/kc_JS.txt)

**Comment by Enngage** [comment]
This is indeed a bug in browser specific bundle (did not affect full bundle). Fixed in `5.5.0`  (https://github.com/Kentico/kentico-cloud-js/pull/115)
