### ISSUE TITLE
Enrich returned data by components from rich text elements

### ISSUE THREAD

**Issue by Simply007** [Kentico/kentico-cloud-js#114]
### Motivation

When developing [Gatsby source plugin for Kentico Cloud](https://github.com/Kentico/gatsby-source-kentico-cloud) I need to have all data that are in KC in one data model to create a GraphQL model form and fill it with data.

Unfortunately, there are no [content components data](https://developer.kenticocloud.com/v1/reference#linked-content). So I am not able to create a model containing data from the content components.

### Proposed solution

I can see two ways, how to solve the issue.

1. Have a separate property of type `ContentItem[]` in the response (Listing and Single as well) with content components (maybe including classic content components modular content).
2. Enrich the rich text element (`RichTextField` in code) by a property linked content containing content components and content items, or split it into two and have `contentComponents` + `linkedItems`.

### Additional context

My use-case is that I am loading all data using `DeliveryClient.items()`. So I don't care where the data is - in case of linked items - they are a part of the response, but in case of content components, there is no data about them. 

I can image somebody that is loading one item containing rich text element with the content components as well as inline linked item and wants to access all data (item itself, linked items, and content components) from the response in structured form (i.e. to create a react/vue/angular).

**Comment by Enngage** [comment]
I've added new `linkedItems` property to `DeliveryItemResponse` and `DeliveryItemsResponse` responses. This property contains flat array of all linked items that were resolved during the item mapping.  I don't think I can pass this information to individual fields or resolvers because a that time items might not be yet resolved. 

Does this satisfies your requirement? I've released this under `5.6.0`

**Comment by Simply007** [comment]
I will try it, thanks.

**Comment by Simply007** [comment]
Raised #137.

**Comment by Enngage** [comment]
Closed via https://github.com/Kentico/kentico-cloud-js/pull/139
