### ISSUE TITLE
CM package uses POST not PUT for updating/upserting assets

### ISSUE THREAD

**Issue by CollierCZ** [Kentico/kentico-cloud-js#133]
### Brief bug description

When attempting to use `.updateAsset()` or `.upsertAsset()`, the SDK uses POST, which is the wrong method for [the endpoint](https://developer.kenticocloud.com/reference#content-management-api-v2-update-asset).

### Repro steps

1. Use CM package
2. Use `.updateAsset()` or `.upsertAsset()`
3. Log errors to console
4. See 400 error - API doesn't support POST

### Expected behavior

The package will use PUT and I will get a 200 response along with an updated asset.

**Comment by Enngage** [comment]
Thanks for submitting the isuse. I believe this has been fixed by https://github.com/Kentico/kentico-cloud-js/pull/129/files , but it has not yet been released. 

I'll release it in upcoming days. Is this required for something or do you have any timeline you need this to work?

**Comment by CollierCZ** [comment]
No rush. Just putting the API reference together and going through each endpoint.

**Comment by CollierCZ** [comment]
@Enngage, this has been released, right?

**Comment by Enngage** [comment]
Yep, its released. Though, there are some changes to API. I will update you
with the review once I can. I've just returned from Vacation.
