### ISSUE TITLE
Add support for add/delete content type snippets to CM

### ISSUE THREAD

**Issue by CollierCZ** [Kentico/kentico-cloud-js#135]
### Motivation

In the first week of March, the ability to [add/delete snippets](https://developer.kenticocloud.com/v1/reference?#add-content-type-snippets-beta) will be added to the CM API.

### Proposed solution

Support added to the CM package.

**Comment by Enngage** [comment]
Released (https://github.com/Kentico/kentico-cloud-js/pull/150)
