### ISSUE TITLE
RichTextElement with links - getHtml() parsing error

### ISSUE THREAD

**Issue by matap** [Kentico/kentico-cloud-js#142]
I have rich text element with links (maybe a hrefs?).
When I call props.element.getHtml(), I see error:

browser-rich-text.parser.js:32 Uncaught Error: Parsing HTML failed:Error: HTML node is invalid. Reason: missing 'data-item-id' attribute
    at BrowserRichTextParser.resolveRichTextField (browser-rich-text.parser.js:32)
    at RichTextResolver.resolveHtml (rich-text.resolver.js:29)
    at RichTextField.resolveHtml (field.mapper.js:197)

Rich text without links is parsed well. 

Tested on versions "kentico-cloud-delivery": 5.7.2 and 5.4.0
Version 5.1.0 works well.

**Comment by Enngage** [comment]
Hey, thanks for reporting this. One question though - are you running this
under node.js or browser? If it's browser, which one?

**Comment by matap** [comment]
Tested on google chrome 73.0.3683.75

**Comment by Enngage** [comment]
It was indeed the case that if you had a 'regular' links in Rich text field, this error would be thrown. However, how did you actually add links to your Rich text field? As far as I know, this is not yet supported. Did you just copy the full `<a ...>` tag as text? 

Anyway, it's a valid point so I added support for regular links in latest beta version `6.0.0-beta.1`

**Comment by matap** [comment]
I added links in standard way. Nothing special

![image](https://user-images.githubusercontent.com/4975601/54642216-57ca4600-4a94-11e9-971d-97249f729823.png)
