### ISSUE TITLE
The create-react-app is not rendering on IE11, due to kentico-cloud-delivery issue

### ISSUE THREAD

**Issue by marjanatwork** [Kentico/kentico-cloud-js#147]
Hi,
My create-react-app application is not rendered on IE11. When I Inspect elements, I see this error:
![errorkentico](https://user-images.githubusercontent.com/48732421/54634386-57ec2680-4a3f-11e9-9bc1-c7f1e1519cbd.png)

and when I click on bundle.js in the error message, I get the following message in bundle.js file:
![errorkentico2](https://user-images.githubusercontent.com/48732421/54634584-c29d6200-4a3f-11e9-9412-8958baa79874.png)

In kentico-cloud-delivery folder in node_moduals there are the following SDKs of kentico:

kentico-cloud-delivery-sdk.browser.umd.min.js
kentico-cloud-delivery-sdk.browser.umd.min.js.map
kentico-cloud-delivery-sdk.umd.js
kentico-cloud-delivery-sdk.umd.js.map
kentico-cloud-delivery-sdk.umd.min.js
kentico-cloud-delivery-sdk.umd.min.js.map

I would appreciate it if you could help me to resolve this issue.

Many thanks,
Marjan

**Comment by Enngage** [comment]
Hi,

This may be related to react issue as described at https://github.com/Kentico/kentico-cloud-js/issues/69 

The code you mentioned actually comes from a 3rd party dependency we have (parse5) and likely the fact its not published in ES5 format which is causing IE to fail. 

A possible workaround is to instruct react to use the `kentico-cloud-delivery-sdk.browser.umd.min.js` umd bundle instead which as all code transpiled to ES5. The issue above contains some information on this as well.

**Comment by marjanatwork** [comment]
Awesome! This solution worked for me. Thank you very much for your good guidance.

**Comment by Simply007** [comment]
Hello @marjanatwork. I've just sent you an invitation to the Kentico GitHub organization, in case you want to stay up to date with our OS projects.
