### ISSUE TITLE
Support setting a baseUrl with no projectId 

### ISSUE THREAD

**Issue by kentico-michaelb** [Kentico/kentico-cloud-js#171]
### Motivation

When a developer wants to hide project-specific data like projectId from their Delivery API calls, they can setup an API proxy that will handle the incoming request from the project and the outgoing request to our API.  When setting the baseUrl to point to the proxy, and setting the projectId to a blank or a null value, the generated url contains a double-slash where the projectId would normally have been.

Example:

let Client = new DeliveryClient({
  projectId: "",
  typeResolvers: typeResolvers,
  previewApiKey: previewApiKey,
  baseUrl: "https://localhost:3000/test"
});

result: :3000/test//items

### Proposed solution

Evaluate if the baseUrl is set, and if the projectId is blank or null, do not append a slash to the url. This slash may be generated here: https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/lib/services/base-delivery-query.service.ts#L192  

### Additional context

This is an active issue for a customer in Intercom.  If you neeed more details or if something is unclear, please reach out to me directly.  Thanks!

**Comment by Enngage** [comment]
I've added support for fully customizing URLs via `proxyUrl` configuration option and updated [docs ](https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/DOCS.md#using-proxy-urls)

You can now use something like this:

```typescript
const client = new DeliveryClient({
  projectId: 'xxx',
  proxyUrl: (data) => {
    return `http://my-proxy.io${data.action}${data.queryString}`; // proxy url with omitted project Id
  }
});
```
