### ISSUE TITLE
Image with id ... was not found in images data

### ISSUE THREAD

**Issue by blhylton** [Kentico/kentico-cloud-js#189]
### Brief bug description

When attempting to get an image that is in a nested component, I get a console error: "Error in render: "Error: Image with id '...' was not found in images data". Inspecting the data shows me that there are indeed no images in my page data.

### Repro steps

1. Insert structured content that contains a rich text element with an image into a rich text editor that has an image embedded in it.
2. Resolve rich text.
3. Page does not render, the error is thrown, no images in data.

### Expected behavior

For my page to render the HTML

### Test environment

 - Platform/OS: MacOS
 - Browser Chrome, Safari, Firefox
 - Version 6.0.0-beta9

### Additional context

Seems to be related to (or possibly is a regression of) https://github.com/Kentico/kentico-cloud-js/issues/165

Just to be a little more clear, the structure of the content is like this:

Rich Text > Custom Component > Rich Text > Image

**Comment by Enngage** [comment]
Hi @blhylton,

Can you let me know how you are using **Rich text** element inside a **Custom element** ? I'm not exactly sure how this would work. 

Additionally, Is it possible for you to share the request url? You get url by calling `getUrl` method on any query or just see the network console tab in your browser. 

Thank you for submitting the issue and any more information you can provide.

**Comment by blhylton** [comment]
In my hurry to write all this out earlier, I forgot to mention that I'm using Vue and I'm attempting to resolve my custom structure into a Vue component, so essentially here is what is happening:

* Call`getHtml()` on root RichTextElement
* Renders typical content (i.e. plain-old-HTML)
* Attempts to render custom component using my model's RichTextResolver
* Sub-component renders wrappers correctly
* Attempt to render RichTextElement, if there is an image in this Element, it fails with the aforementioned error

This seems to be happening because the images in the child RichTextElement are not in the parent's image array. Obviously, they shouldn't need to be, but even if I call `getHtml()` or `resolveHtml()` in my custom components RichTextResolver, it tries to find them again when the HTML from calling either method "bubbles up" to the top.

This is honestly pretty frustrating since I can console.log the html and see that the correct image tag is already there in what is being returned from my custom RichTextResolver, but it seems like it still wants those images to be available in the root element.

**Comment by Enngage** [comment]
Can you please share the request **url** or the **full response** you get from KC? This is really the best way how I can further investigate this issue.

**Comment by blhylton** [comment]
Oh, I just saw you responded while I was typing that last bit.

Okay, so I have a custom element so that my client will be able to easily create two-column layouts and embed them in an already existing Rich Text Element. So my Content Type (I keep saying Component for some reason) has a Left Content and Right Content field that are Rich Text Elements.

The particular request URL that I'm testing with is https://deliver.kenticocloud.com/646ae72d-cb1e-0012-776a-08fabe8ce301/items?system.type=page&elements.friendly_url=earn&depth=30 but it has happened on other endpoints.

I'll admit, this could be something I'm doing wrong in Vue as well. Had to pick it up for this project so I could be misusing something.

**Comment by Enngage** [comment]
Nice coincidence :-) 

Thank you for the url. I'll have a look at this on Monday Morning and will update you as I go. 

From what you said it seems the issue might be within the SDK. I remember having the same error before and thought it was solved for good (there are some tests for this as well). Maybe your scenario is a bit specific which I have not covered yet.

**Comment by blhylton** [comment]
So, I did manage to fix it for my purposes, although I don't yet know if this will have any side effects.

The key to fixing it was [in browser-rich-text.parser.ts starting at line 158](https://github.com/Kentico/kentico-cloud-js/blob/delivery%406.0.0-beta.9/packages/delivery/lib/parser/adapters/browser-rich-text.parser.ts#L158) coupled with my comment from earlier:

> This seems to be happening because the images in the child RichTextElement are not in the parent's image array. Obviously, they shouldn't need to be, but even if I call `getHtml()` or `resolveHtml()` in my custom components RichTextResolver, it tries to find them again when the HTML from calling either method "bubbles up" to the top.

Since the image resolver is only looking for the data-attributes, it was trying to re-resolve the images even though I had already "pre-compiled" the component. My quick fix was to take the pre-compiled component, find the `imgs` inside, and delete the `imageId` dataset. This obviously isn't ideal, but it is at least working for now.

I think the solution may be to check for both the existence of that data attribute (to verify that it is a content item) and that the image source is non-existent or empty (to verify that it hasn't already been resolved). If it weren't so late here I would try to set up a pull request, but it's after 4 AM right now ;). If I find time in the next few days, I'll try to get a merge request in to fix this. That being said, I don't know enough about how this resolver works to know if this would have any other side effects.

**Comment by Enngage** [comment]
@blhylton Is there any chance you can also send me the classes & type resolvers you have? I've been trying to register my own classes & rich text resolvers on my end, but so far I haven't been able to reproduce the error. 

I guess I'm still missing something and having your full context would help me understand your scenario.

**Comment by blhylton** [comment]
Given that this is for a client, I'm not sure I want to post all of that publicly. Do you have an email or some other private comm channel where I can send it to you?

**Comment by Enngage** [comment]
Yeah, sure, feel free to use my github e-mail -- https://github.com/Enngage

**Comment by blhylton** [comment]
Alright, you should receive an email shortly.

**Comment by Enngage** [comment]
@blhylton This has been a bit more challenging and we will likely have to revisit the way images are resolved within nested linked items some time in future. The main problem is within the fact that `images` are part of the `richText` field and if you have nested resolving, there is no field context as we can only know the root field on which the getHtml is called. I've solved it currently by going through all rich text fields within content item and searching for image there. 

Can you try removing your temporary fix and updating to latest version `6.0.0-beta.10` and see how that works?

**Comment by blhylton** [comment]
It appears that that did fix my issue. I'll go ahead and close this, but I wouldn't mind continuing to discuss how to improve this since we have a few clients that will likely be using this in the future.
