### ISSUE TITLE
Web link crashes link resolver

### ISSUE THREAD

**Issue by kenticomartinh** [Kentico/kentico-cloud-js#195]
### Brief bug description

When resolving rich text with a web link, the resolver crashes with the following error:

![image](https://user-images.githubusercontent.com/11004903/58877336-b769e200-86d0-11e9-8fb8-38af5f0c568c.png)

### Repro steps

1. Add web link to some content which is displayed on React sample site
2. Display the content on live site
3. The site crashes

![image](https://user-images.githubusercontent.com/11004903/58877407-e3856300-86d0-11e9-9b07-ead7eec1ff52.png)

### Expected behavior

All types of links should be properly resolved

### Test environment

 - Platform/OS: React
 - Browser Chrome
 - SDK Version 5.7.2

**Comment by Enngage** [comment]
Thank you for the detailed description. This issue was indeed a problem in `5.7.2` and it is now fixed in beta `6.0.x`
