### ISSUE TITLE
Browser distribution is not IE11 complainant 

### ISSUE THREAD

**Issue by ematipico** [Kentico/kentico-cloud-js#197]
### Brief bug description

While importing the browser distribution inside my bundle, it turns out that it's not fully compatible as it contains a `Symbol` at the end of the file:

`var e=Symbol("codename")`

Which breaks on IE11.

### Repro steps

1. Import the browser umd distribution (doing it with webpack in my case)
2. Run it on a browser

### Expected behavior

It should work.
Browser distribution doesn't contains `class`, so it should not contains `Symbol` too.

### Test environment

 - Platform/OS: Windows
 - Browser IE
 - Version 11

### Screenshots

Add links to screenshots, if possible.

**Comment by ematipico** [comment]
`Symbol("codename")` is coming from `reflect-metadata`, which is a dependency. What's the suggested solution for this case?

**Comment by Enngage** [comment]
@ematipico Can you try using this legacy bundle and let me know how that works? 
[kentico-cloud-delivery-sdk.browser.legacy.umd.min.zip](https://github.com/Kentico/kentico-cloud-js/files/3257028/kentico-cloud-delivery-sdk.browser.legacy.umd.min.zip)

**Comment by ematipico** [comment]
Thanks for your answer! I am using the browser umd version as workaround of this issue https://github.com/Kentico/kentico-cloud-js/issues/94. 

I eventually made it working by sticking babel polyfills at the beginning of the generated bundle. This solution works!

**Comment by Enngage** [comment]
Great to hear that :-) I'll be releasing new `legacy` bundle for both CM and Delivery starting from the next releases. Its definitely good you brought this up again :)

**Comment by ematipico** [comment]
Thanks! This is really appreciated!
