### ISSUE TITLE
SPIKE: Automatic generation for the changelog.md 

### ISSUE THREAD

**Issue by Enngage** [Kentico/kentico-cloud-js#63]
Validate possibilities for an automatic generation for changelog.md.

Mind that this is a `monorep` repository. Provide the best practice to apply discovered approach for all the repositories (at least all our SDKs).

**Comment by petrsvihlik** [comment]
what are the benefits?

**Comment by ChristopherJennings** [comment]
Based on quick research and some quick thoughts, it seems to be pretty standard in the JS community. Also, having changelog notes with the repo itself rather than only in GH seems like a good plan as well. Finally, it allows contributors to make suggestions and contributions to the release notes with their PRs.

**Comment by petrsvihlik** [comment]
I'm wondering whether it'd be possible to generate the MD from releases...thoughts?

**Comment by Domitnator** [comment]
Maybe take a look at [semantic-release](https://github.com/semantic-release/semantic-release)? Semantic release has a [plugin ](https://github.com/semantic-release/git)which can generate a changelog.md!

**Comment by Enngage** [comment]
It seems we are unable to fully use the semantic-release because it does not support `monorepo` architecture we use for this repository. The problem with releases right now is that they are not 'package' specific. 

I would likely proceed by manually creating/managing CHANGELOG.md files for each of the packages.

**Comment by Simply007** [comment]
@Enngage 
Manual generation of the changelog would remove the one, and I think the most important, benefit that allows people to add release note proposal via pull request.

If there is a way how to generate changelog automatically and repo independent, I would vote for it. But we need to make it in all our repositories, or at least all our SDKs.

I recommend to close this issue, create an internal spike, how to generate changelog. After the spike is done eventually raise issues across of all our SKDs.

**Comment by Enngage** [comment]
I've setup `lerna-changelog` which does support monorepo and should help generating changelogs. For this to work, all PRs need to be tagged (as described in main readme) and tags need to be created for each release and package so that we can track changes to each package.
