### ISSUE TITLE
Ability to map response (expose response mapper)

### ISSUE THREAD

**Issue by Enngage** [Kentico/kentico-cloud-js#86]
In some cases we might want to store raw json/response (e.g. in cache) and still leverage strongly typed models. For this reason, we need to a way of mapping this string/json back to original models. For this to work, we should expose response mappers in a better way so that its easy to use by developers.

**Comment by Simply007** [comment]
Currently, it is possible to do that like that:
https://github.com/Simply007/apollo-test/blob/master/src/App.js#L23

**Comment by Enngage** [comment]
Fixed by https://github.com/Kentico/kentico-cloud-js/pull/218
