### ISSUE TITLE
Type 'IBaseResponse' is not generic.

### ISSUE THREAD

**Issue by ematipico** [Kentico/kentico-cloud-js#87]
### Brief bug description

1. Upgraded kentico-cloud-delivery from 4 to 5
2. Got the following error
```
node_modules/kentico-cloud-delivery/_commonjs/mappers/response.mapper.d.ts(53,32):
TS2315: Type 'IBaseResponse' is not generic.
```

### Repro steps

1. Install the latest
2. Kick off the project

### Expected behavior

It should compile without issue

### Test environment

 - Platform/OS: macOS Mojave
 - Browser Chrome
 - Version latest

**Comment by Enngage** [comment]
Thanks for the info, I think this is because I didn't update references to newer core version when publishing Today's version. Can you please try `5.2.1` I just published and let me know if that helps?

**Comment by ematipico** [comment]
The latest version looks good! Thanks for the quick fix!
