### ISSUE TITLE
Move npm packages under the official kentico organization

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kentico-cloud-js#90]
see the password server for credentials

**Comment by Enngage** [comment]
I believe the package already is under Kentico organization (I transfered project using npm admin a while ago). You can also see community members (that are part of Kentico org) as **collaborators** on npm: 

![npm](https://user-images.githubusercontent.com/7137351/50296793-89bf1280-047b-11e9-8110-ca63e3382d82.png)

Closing for now, but feel free to reopen if I'm missing something.

**Comment by Enngage** [comment]
All packages in this repo are now under Kentico organization.

**Comment by petrsvihlik** [comment]
thx!
