### ISSUE TITLE
Not compatible with angular 7

### ISSUE THREAD

**Issue by r3plica** [Kentico/kentico-cloud-js#93]
### Brief bug description

The class kentico-cloud-angular-http-service throws an error: error TS2420: Class 'AngularHttpService' incorrectly implements interface 'IHttpService'.  Type 'AngularHttpService' is missing the following properties from type 'IHttpService': put, delete

### Repro steps

Upgrade to Angular 7.2.1

**Comment by r3plica** [comment]
just so you know, I tried doing this myself:

`    import { HttpClient } from '@angular/common/http';
    import { IBaseResponse, IHttpGetQueryCall, IHttpPostQueryCall, IHttpQueryOptions, IHttpService } from 'kentico-cloud-core';
    import { Observable } from 'rxjs';
    export declare class AngularHttpService implements IHttpService {
        private http;
        constructor(http: HttpClient);
        get<TError extends any>(call: IHttpGetQueryCall<TError>, options?: IHttpQueryOptions): Observable<IBaseResponse>;
        post<TError extends any>(call: IHttpPostQueryCall<TError>, options?: IHttpQueryOptions): Observable<IBaseResponse>;
        put<TError extends any>(call: IHttpPostQueryCall<TError>, options?: IHttpQueryOptions): Observable<IBaseResponse>;
        delete<TError extends any>(call: IHttpPostQueryCall<TError>, options?: IHttpQueryOptions): Observable<IBaseResponse>;
        private getAngularHeaders(headers?);
    }
`
But it now moans about this:

ERROR in node_modules/kentico-cloud-angular-http-service/angular-http.service.d.ts(7,103): error TS2314: Generic type 'IBaseResponse<TRawData>' requires 1 type argument(s).
node_modules/kentico-cloud-angular-http-service/angular-http.service.d.ts(8,105): error TS2314: Generic type 'IBaseResponse<TRawData>' requires 1 type argument(s).
node_modules/kentico-cloud-angular-http-service/angular-http.service.d.ts(9,104): error TS2314: Generic type 'IBaseResponse<TRawData>' requires 1 type argument(s).
node_modules/kentico-cloud-angular-http-service/angular-http.service.d.ts(10,107): error TS2314: Generic type 'IBaseResponse<TRawData>' requires 1 type argument(s).

**Comment by Enngage** [comment]
@r3plica this looks like a mismatch in versions of the `kentico-cloud-core` that you have installed and the one that `kentico-cloud-angular-http-service` actually expects. 

Anyway, I've updated the angular service package to use latest `kentico-cloud-core` and released it under `2.1.0` so try updating everything to latest version and it should be ok.
