### ISSUE TITLE
Delivery client is not working in Internet Explorer

### ISSUE THREAD

**Issue by xduseko** [Kentico/kentico-cloud-js#94]
### Brief bug description

Delivery client installed using webpack (Angular CLI) is not working in latest Internet Explorer. It packs dependency with `const` keyword.

### Repro steps

1. Install Angular CLI
2. Generate new project
3. Install delivery client using `npm i -S...`
4. Use delivery client in way as cloud-sample-angular-pwa-app does
5. Test website on Internet Explorer 11
6. Open developer console and see error

### Expected behavior

What the correct behavior is?

### Test environment

 - Platform/OS: Windows 10
 - Browser: Internet Explorer
 - Version 11

### Screenshots

![image](https://user-images.githubusercontent.com/9591957/51537053-be910180-1e4d-11e9-9d76-375cdba70a44.png)

![image](https://user-images.githubusercontent.com/9591957/51537078-cf417780-1e4d-11e9-95ff-88ffe662582e.png)

**Comment by Enngage** [comment]
I believe this is the responsibility of Angular CLI (and its configuration) to compile a code certain format (in your case that would likely be ES5 + polyfills for IE). 

For example, does this [demo ](https://stackblitz.com/edit/kentico-cloud-delivery-sample) work for you in IE? It does work on my local IE11 instance and so this shouldn't be a library issue. 

Angular stop shipping IE polyfills from certain version by default so Angular apps do not work there unless you specifically include polyfills yourself. Maybe this [SO ](https://stackoverflow.com/questions/35140718/angular-2-4-5-not-working-in-ie11)will help?

**Comment by xduseko** [comment]
Thanks for the response. The demo is working in my IE 11 instance. It it compiled using official typescript compiler? I couldn't find any configuration.

I use following configuration in my project:
![image](https://user-images.githubusercontent.com/9591957/51541602-855e8e80-1e59-11e9-9533-60c1b1954af2.png)

Keywords like `const`, `let` and any other language specific features in `.ts` files are compiled to ES5 correctly (to `var`). But I believe typescript is not compiling `.js` files, so files like `/node_modules/kentico-cloud-delivery/node_modules/parse5/lib/common/doctype.js` are not actually compiled, they are only bundled by webpack.

Does the `kentico-cloud-delivery` require babel?

**Comment by Enngage** [comment]
I'm not exactly sure how Angular internally compiles the code of 3rd party libraries (though you still need those polyfills for IE).

 As a _quick fix_ you can add `kentico-delivery-client` as an UMD bundle to your angular scripts (`angular.json` -> `scripts`), however using ES6 imports is so much better. 

I can try running my own Angular 7 app with delivery client Tomorrow to see what I get.

**Comment by xduseko** [comment]
Thanks, I will try that if necessary. I would appreciate if you could let me know whether your Angular 7 app is working.
I have tried https://github.com/Kentico/cloud-sample-angular-pwa-app, but it depends on the older version of kentico-delivery-client that doesn't need `parse5`. Also it has many other issues in IE 11.

**Comment by Enngage** [comment]
@xduseko I've updated my demo angular app to Angular 7 and it runs ok even in IE 11. Did you really include those Angular polyfills for IE? 

You can find my Angular repo [here](https://github.com/Enngage/KenticoCloudSampleAngularApp) and online demo [here](https://enngage.github.io/KenticoCloudSampleAngularApp/)

Angular made it really easy to include those polyfills - you only have to uncomment them in `polyfills.ts` file that comes with angular. See what I have - https://github.com/Enngage/KenticoCloudSampleAngularApp/blob/master/src/polyfills.ts
 
For now I'm closing this issue as it doesn't seem to be relevant to this repository. Please do let me know if the above works for you.

**Comment by Enngage** [comment]
Seems like I wasn't entirely correct - I missed the fact that my sample app already uses UMD bundle defined in ts.config:

```
   "paths": {
      "kentico-cloud-delivery": [
        "node_modules/kentico-cloud-delivery/_bundles/kentico-cloud-delivery-sdk.browser.umd.min.js"
      ]
    },
```

With ES6 imports, I get the same Exception in IE11 as you do. I'm not sure if this is something I can fix, but I'll take a further look.

**Comment by xduseko** [comment]
I have discovered something that is worth to note. I'm using angular cdk from material lib and it also depends on parse5 library.

```
my-project@0.0.0
+-- @angular/animations@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/cdk@7.2.1
| +-- parse5@5.1.0
| `-- tslib@1.9.3 deduped
+-- @angular/common@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/compiler@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/core@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/forms@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/platform-browser@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/platform-browser-dynamic@7.1.4
| `-- tslib@1.9.3 deduped
+-- @angular/router@7.1.4
| `-- tslib@1.9.3 deduped
+-- core-js@2.6.1
+-- kentico-cloud-delivery@5.2.2
| +-- kentico-cloud-core@1.3.0
| | `-- axios@0.18.0
| |   +-- follow-redirects@1.6.1
| |   | `-- debug@3.1.0
| |   |   `-- ms@2.0.0
| |   `-- is-buffer@1.1.6
| +-- parse5@5.1.0
| `-- reflect-metadata@0.1.12
+-- rxjs@6.3.3
| `-- tslib@1.9.3 deduped
+-- tslib@1.9.3
`-- zone.js@0.8.26
```

When the application starts, warning appears in the browser console.
```
client:154 ./node_modules/parse5/lib/index.js 55:23-49
Critical dependency: the request of a dependency is an expression
```

Based on my little research this is webpack complaining about wildcard imports. I have found several in kentico-cloud-delivery, but none in angular cdk.

```
import * as parse5 from 'parse5';
```

**Comment by Enngage** [comment]
Thats interesting.. I noticed that parse5 is listed as an [optional dependency in angular material cdk](https://github.com/angular/material2/blob/3192dfa1f31012b6a3c87aa3b08b56a15ce75386/src/cdk/package.json#L33) so maybe its not even included /used in your Angular app. 

I'll have a look at this and try to get rid of the `import * as parse 5 from 'parse5'`. If that would be possible and fixed this issue, that would be awesome. It might also lower the size of bundle which would be very nice addition. Will see.

Anyway, I found a `workaround` you could use for the moment. In your main `ts.config` use an alias to a browser only UMD bundle:

```
"paths": {
      "kentico-cloud-delivery": [
        "node_modules/kentico-cloud-delivery/_bundles/kentico-cloud-delivery-sdk.browser.umd.min.js",
      ]
    },
```

This bundle does not even contain `parse5` and works fine in IE11. It also shrinks the size of lib by 50% so its even recommended if you don't plan on using Angular universal.

However, this breaks typings so you need to redefine the module. I was able do that by adding following code into the `typings.d.ts`:

```
declare module 'kentico-cloud-delivery' {
  export * from 'node_modules/kentico-cloud-delivery/_es2015';
}
```

**Comment by Enngage** [comment]
Closing for now as the above should be be enough as a workaround for the moment. Hopefully, we will be able to get rid of parse5 alltogether at some point.

**Comment by rubenberendsen** [comment]
Is it possible to fix this also for package and not only for the browser UDM bundle?

**Comment by Enngage** [comment]
Maybe I'm missing something, but if you are not using browser UMD bundle it implies that you need to run code on server = **node.js** in which case browser is not to execute the code and therefore the question becomes irrelevant. 

If you can share more details, I might be able to help in another way.

**Comment by ematipico** [comment]
I bumped into this issue.

Background: Kentico client has to run into Node AND Browser. When I build everything with webpack, what I get inside the built version is the `umd.js` that contains the `class` keywords. This breaks the usage in IE11.
